<?php

/**
 * Custom function to handle errors
 * This will convert errors into exceptions
 * @param $errno int          gives the type of error
 * @param $errstr string      gives the error message
 * @param $errfile string     gives the file where the error occurs
 * @param $errline int        gives the line in the file
 *
 * The parameters above are automatically generated by PHP and passed to the function.
 * @throws Exception
 */

function errorHandler(int $errno, string $errstr, string $errfile, int $errline): void
{
    // check error isn’t excluded by server settings
    if (!(error_reporting() & $errno)) {
        return;
    }
    throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
}
