<?php

/**
 * General Function to handle any exception
 * It will be triggered by PHP when an exception occurs
 *
 * @param $e Exception an object with information about the exception
 * automatically generated by PHP when the function is triggered.
 */

function exceptionHandler(Exception $e): void
{
    if (DEVELOPMENT_MODE) {
        echo  " Message: " . $e->getMessage() . "File: " . $e->getFile() . " Line: " . $e->getLine();
    } else {
        echo "Internal Server Error (status code 500)";
    }
}
